- hosts: workstation
  gather_facts: false
  roles:
  - name: osp-facts  
  tasks:
  - name: Smoke test to verify URL availability
    uri:
      url: "http://localhost:8080"
      return_content: yes
      status_code: 200
    register: webpage  

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"

- hosts: appsdb
  gather_facts: false
  tasks:
  - name: Smoke test to verify DB availability
    become: true
    become_user: postgres
    postgresql_info:
    register: pg_databases_info
 
  - debug:
      var: pg_databases_info    