---

- name: Installing {{ lb_app }}
  yum:
    name: "{{ lb_app }}"
    state: latest
  notify: restart_app

- name: Configuring {{ lb_app }}
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart_app

- name: Enable and start {{ lb_app }}
  service:
    name: "{{ lb_app }}"
    enabled: yes
    state: started