---

- name: Installing {{ http_app }}
  yum:
    name: "{{ http_app }}"
    state: latest
  notify:
    - restart_app

- name: Creating {{ http_app }} web root directory
  file:
    path: "{{ http_web_root }}"
    state: directory

- name: Create index.html for {{ http_app }} on {{ http_web_root }}
  template:
    src: index.html.j2
    dest: "{{ http_web_root }}/index.html"
    mode: 0644
  notify:
    - restart_app

- name: Enable {{ http_app }} to start at boot and start
  service:
    name: "{{ http_app_service }}"
    enabled: yes
    state: started